apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    app: project-voting-app
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containersPort: 6379
