apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: node-namespace
  labels:
    app: node-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-label
  template:
    metadata:
      labels:
        app: node-label
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: node-app
          image: iolowookere217/my-nodeapp:v1
          ports:
            - name: tcp
              containerPort: 5000
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /healthz # Replace with the path to your readiness endpoint
              port: 5000 # Replace with the container port
            initialDelaySeconds: 5 # Delay before the first probe
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: node-namespace
  labels:
    app: node-label
spec:
  selector:
    app: node-label
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
