version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@3.1.0

commands:
  destroy-cluster:
    description: Destroy EKS Cluster.
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            eksctl delete cluster --name devopsproject

  install-kubectl-and-eksctl:
    description: install kubectl and eksctl
    steps:
      - run:
          name: Installing kubectl and eksctl
          command: |
            yum install tar gzip -y
            curl --silent --location -o /usr/local/bin/kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
            chmod +x /usr/local/bin/kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
            kubectl version --client

            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            mv /tmp/eksctl /usr/local/bin
            eksctl version
jobs:
  lint-app:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Pythdon linting
          command: |
            pip install --upgrade pip
            pip install flake8  
            flake8 myapp.py

  build-and-push-node1:
    machine: true

    steps:
      - checkout
      - run:
          name: Load .env File
          command: |
            echo "$DOTENV_FILE" > .env
      - run:
          name: Build and Push Docker Image for deploy
          command: |
            docker build -t iolowookere217/my-webapp:v1 .
            echo "$DOTENV_FILE" | docker login -u iolowookere217 --password-stdin
            docker push iolowookere217/my-webapp:v1

  delete-existing-ec2-resources:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Delete if Stack Exists
          command: |
            aws cloudformation delete-stack --stack-name devops-stack --region us-east-1
            aws cloudformation wait stack-delete-complete --stack-name devops-stack --region us-east-1

  # Define a separate job for creating the stack
  create-ec2-resources-after-deletion:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Configure AWS Credentials
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-east-1
      - run:
          name: Creating EC2 resources
          command: |
            aws cloudformation create-stack \
              --stack-name devops-stack \
              --template-body file://cf.yml \
              --region us-east-1 
            aws cloudformation wait stack-create-complete --stack-name devops-stack --region us-east-1

  # create-ec2-resources:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: Check if Stack Exists
  #         command: |
  #           if aws cloudformation describe-stacks --stack-name devops-stack --region us-east-1; then
  #             aws cloudformation delete-stack --stack-name devops-stack --region us-east-1
  #             aws cloudformation wait stack-delete-complete --stack-name devops-stack --region us-east-1
  #           fi

  create-eks-cluster-app:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - install-kubectl-and-eksctl
      - run:
          name: Creating K8S cluster
          command: |
            echo
            eksctl create cluster \
            --name devopsproject \
            --region us-east-1 \
            --with-oidc \
            --ssh-access \
            --ssh-public-key new-key
            --node-zones us-east-1a
            kubectl get nodes -o wide
            kubectl create namespace node-namespace
            aws eks update-kubeconfig --name devopsproject --region us-east-1
      - run:
          name: Deploying v1
          command: |
            kubectl apply -f deploy.yml
      - destroy-cluster

  smoke-test-v1:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - install-kubectl-and-eksctl
      - run:
          name: Installing dependencies
          command: |
            echo
            yum install jq -y
      - destroy-cluster

workflows:
  the_jobs:
    jobs:
      - lint-app
      - build-and-push-node1:
          requires: [lint-app]
      - delete-existing-ec2-resources:
          requires: [build-and-push-node1]
      - create-ec2-resources-after-deletion:
          requires: [delete-existing-ec2-resources]
      - create-eks-cluster-app:
          requires: [create-ec2-resources-after-deletion]
      - smoke-test-v1:
          requires: [lint-app]
